baseURL: "https://portfolio254.netlify.app/"
languageCode: en-us
title: My Portfolio
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: My Portfolio
  description: "Passionate Full Stack Web Developer | Transforming Ideas into Digital Reality"
  keywords: [Blog, Portfolio, Software Engineer, Full Stack Web Developer]
  author: Joseph Miseda
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  customCSS: ["css/styles.css"]

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Joseph Miseda Mbime"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there! 👋"
    Content: |
      I'm Kallias254, code whisperer 🪄, slayer of bugs and glitches ⚔️, always on a quest to make your web experience smoother. I'm a full-stack web developer and debugger extraordinaire.

      When I'm not wrangling pixels or debugging demons, you'll find me riding the waves in Kilifi ☀️, slaying digital dragons in video games , or getting lost in a good sci-fi thriller.

      So, whether you need a website that wows ✨, or just someone to geek out about the latest tech trends , let's connect! I'm always up for a challenge, a collaboration, or simply a good conversation about the magic of code ☕️.

  socialIcons:
    - name: twitter
      url: "https://twitter.com/Miseda254"
    - name: github
      url: "https://github.com/Kallias254"
    - name: email
      url: "https://mail.google.com/mail/?view=cm&fs=1&to=misedajoseph@gmail.com"
   
  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    # URL: "https://github.com/<path_to_repo>/content"
    # Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: blog
      name: Blog
      url: /post/
      weight: 4
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 2
    - identifier: resume
      name: Resume
      url: "https://www.dropbox.com/s/fwm9vp3bojz7tvj/Get%20Started%20with%20Dropbox.pdf?dl=0"
      weight: 3
    - identifier: home
      name: Home
      url: /
      weight: 1
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
  # highlight:
    # noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
services:
  disqus:
    shortname: "portfolio-wvesaptkih"
